"""Terminal theming backends (Konsole default; kitty / Alacritty / xterm optional).

Each backend turns the effective Material palette plus the user's
:class:`~plasmacolorizer.core.terminal_settings.TerminalSettings` into a color
scheme for that terminal. Konsole gets the full live-reload treatment; the
file-based terminals write an include-able config the terminal picks up on its
next launch (Alacritty reloads live).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from plasmacolorizer.core import konsole_scheme
from plasmacolorizer.core.palette import MaterialPalette, rgb_to_hex
from plasmacolorizer.core.terminal_settings import (
    DEFAULT_TERMINAL_ID,
    TerminalSettings,
    load_terminal_settings,
    parse_hex_rgb,
)

RGB = tuple[int, int, int]


@dataclass(frozen=True)
class ResolvedTerminalColors:
    """Concrete colours + typography after applying overrides to the palette."""

    background: RGB
    foreground: RGB
    cursor: RGB
    normal: list[RGB]
    bright: list[RGB]
    opacity: float
    font_family: str
    font_size: float
    bold_intense: bool


def _override_rgb(value: str) -> RGB | None:
    return parse_hex_rgb(value) if value else None


def resolve_terminal_colors(
    pal: MaterialPalette,
    settings: TerminalSettings,
) -> ResolvedTerminalColors:
    """Blend palette-derived terminal colours with the user's manual overrides."""
    bg, _bg_i, _bg_f = konsole_scheme._konsole_backgrounds(pal)
    fg, _fg_i, _fg_f = konsole_scheme._konsole_foregrounds(pal, bg)
    normal, bright, _faint = konsole_scheme._konsole_ansi_sets(pal)
    cursor = pal.colors.get("primary", fg)

    bg_o = _override_rgb(settings.background_override)
    fg_o = _override_rgb(settings.foreground_override)
    accent_o = _override_rgb(settings.accent_override)
    if bg_o is not None:
        bg = bg_o
    if fg_o is not None:
        fg = fg_o
    if accent_o is not None:
        cursor = accent_o

    return ResolvedTerminalColors(
        background=bg,
        foreground=fg,
        cursor=cursor,
        normal=list(normal),
        bright=list(bright),
        opacity=max(0.0, min(1.0, float(settings.opacity))),
        font_family=settings.font_family.strip(),
        font_size=float(settings.font_size),
        bold_intense=bool(settings.bold_intense),
    )


# --------------------------------------------------------------------- Konsole


def _apply_konsole(pal: MaterialPalette, settings: TerminalSettings) -> tuple[bool, str]:
    colors = resolve_terminal_colors(pal, settings)
    font = (
        konsole_scheme.konsole_font_string(colors.font_family, colors.font_size)
        if colors.font_family
        else None
    )
    return konsole_scheme.apply_konsole_scheme(
        pal,
        opacity=colors.opacity,
        background_override=_override_rgb(settings.background_override),
        foreground_override=_override_rgb(settings.foreground_override),
        bold_intense=colors.bold_intense,
        font=font,
    )


# ----------------------------------------------------------------------- kitty


def kitty_config_dir() -> Path:
    return Path(os.path.expanduser("~/.config/kitty"))


def render_kitty_theme(colors: ResolvedTerminalColors) -> str:
    """Kitty ``.conf`` fragment (``include``-able from ``kitty.conf``)."""
    lines = [
        "# Generated by PlasmaColorizer — do not edit (regenerated on apply).",
        f"foreground {rgb_to_hex(colors.foreground)}",
        f"background {rgb_to_hex(colors.background)}",
        f"cursor {rgb_to_hex(colors.cursor)}",
        f"background_opacity {colors.opacity:g}",
    ]
    if colors.font_family:
        lines.append(f"font_family {colors.font_family}")
        lines.append(f"font_size {colors.font_size:g}")
    for i, rgb in enumerate(colors.normal):
        lines.append(f"color{i} {rgb_to_hex(rgb)}")
    for i, rgb in enumerate(colors.bright):
        lines.append(f"color{i + 8} {rgb_to_hex(rgb)}")
    return "\n".join(lines) + "\n"


_KITTY_INCLUDE = "include plasmacolorizer.conf"


def _ensure_kitty_include(kitty_conf: Path) -> None:
    existing = ""
    if kitty_conf.is_file():
        existing = kitty_conf.read_text(encoding="utf-8", errors="replace")
        if _KITTY_INCLUDE in existing:
            return
    prefix = "" if (not existing or existing.endswith("\n")) else "\n"
    with kitty_conf.open("a", encoding="utf-8") as fh:
        fh.write(f"{prefix}{_KITTY_INCLUDE}\n")


def _reload_kitty() -> bool:
    """kitty reloads its config on SIGUSR1 — nudge every running instance."""
    pkill = shutil.which("pkill")
    if not pkill:
        return False
    try:
        subprocess.run([pkill, "-USR1", "-x", "kitty"], check=False, timeout=4)
        return True
    except (OSError, subprocess.SubprocessError):
        return False


def _apply_kitty(pal: MaterialPalette, settings: TerminalSettings) -> tuple[bool, str]:
    colors = resolve_terminal_colors(pal, settings)
    cfg_dir = kitty_config_dir()
    cfg_dir.mkdir(parents=True, exist_ok=True)
    theme_path = cfg_dir / "plasmacolorizer.conf"
    theme_path.write_text(render_kitty_theme(colors), encoding="utf-8")
    _ensure_kitty_include(cfg_dir / "kitty.conf")
    reloaded = _reload_kitty()
    tail = "; reloaded running kitty" if reloaded else "; restart kitty to apply"
    return True, f"wrote {theme_path}{tail}"


# ------------------------------------------------------------------- Alacritty


def alacritty_config_dir() -> Path:
    return Path(os.path.expanduser("~/.config/alacritty"))


def _toml_hex(rgb: RGB) -> str:
    r, g, b = rgb
    return f'"0x{r:02x}{g:02x}{b:02x}"'


def render_alacritty_theme(colors: ResolvedTerminalColors) -> str:
    """Alacritty TOML fragment (imported from ``alacritty.toml``)."""
    n = colors.normal
    b = colors.bright
    lines = [
        "# Generated by PlasmaColorizer — do not edit (regenerated on apply).",
        f"[colors.primary]\nbackground = {_toml_hex(colors.background)}\n"
        f"foreground = {_toml_hex(colors.foreground)}",
        f"[colors.cursor]\ncursor = {_toml_hex(colors.cursor)}",
        "[colors.normal]\n"
        f"black = {_toml_hex(n[0])}\nred = {_toml_hex(n[1])}\n"
        f"green = {_toml_hex(n[2])}\nyellow = {_toml_hex(n[3])}\n"
        f"blue = {_toml_hex(n[4])}\nmagenta = {_toml_hex(n[5])}\n"
        f"cyan = {_toml_hex(n[6])}\nwhite = {_toml_hex(n[7])}",
        "[colors.bright]\n"
        f"black = {_toml_hex(b[0])}\nred = {_toml_hex(b[1])}\n"
        f"green = {_toml_hex(b[2])}\nyellow = {_toml_hex(b[3])}\n"
        f"blue = {_toml_hex(b[4])}\nmagenta = {_toml_hex(b[5])}\n"
        f"cyan = {_toml_hex(b[6])}\nwhite = {_toml_hex(b[7])}",
        f"[window]\nopacity = {colors.opacity:g}",
    ]
    if colors.font_family:
        lines.append(
            f"[font]\nsize = {colors.font_size:g}\n"
            f'[font.normal]\nfamily = "{colors.font_family}"'
        )
    return "\n\n".join(lines) + "\n"


def _ensure_alacritty_import(main_toml: Path, theme_path: Path) -> None:
    import_line = f'import = ["{theme_path}"]'
    if not main_toml.is_file():
        main_toml.write_text(import_line + "\n", encoding="utf-8")
        return
    text = main_toml.read_text(encoding="utf-8", errors="replace")
    if str(theme_path) in text:
        return
    prefix = "" if (not text or text.endswith("\n")) else "\n"
    with main_toml.open("a", encoding="utf-8") as fh:
        fh.write(f"{prefix}{import_line}\n")


def _apply_alacritty(pal: MaterialPalette, settings: TerminalSettings) -> tuple[bool, str]:
    colors = resolve_terminal_colors(pal, settings)
    cfg_dir = alacritty_config_dir()
    cfg_dir.mkdir(parents=True, exist_ok=True)
    theme_path = cfg_dir / "plasmacolorizer.toml"
    theme_path.write_text(render_alacritty_theme(colors), encoding="utf-8")
    _ensure_alacritty_import(cfg_dir / "alacritty.toml", theme_path)
    return True, f"wrote {theme_path} (Alacritty live-reloads config)"


# ----------------------------------------------------------------------- xterm


def xterm_resources_path() -> Path:
    from plasmacolorizer.conky.settings_store import config_dir

    return config_dir() / "xterm.Xresources"


def render_xterm_resources(colors: ResolvedTerminalColors) -> str:
    """X resources for xterm/UXTerm (merge with ``xrdb``)."""
    lines = [
        "! Generated by PlasmaColorizer — do not edit (regenerated on apply).",
        f"*background: {rgb_to_hex(colors.background)}",
        f"*foreground: {rgb_to_hex(colors.foreground)}",
        f"*cursorColor: {rgb_to_hex(colors.cursor)}",
    ]
    for i, rgb in enumerate(colors.normal):
        lines.append(f"*color{i}: {rgb_to_hex(rgb)}")
    for i, rgb in enumerate(colors.bright):
        lines.append(f"*color{i + 8}: {rgb_to_hex(rgb)}")
    if colors.font_family:
        lines.append(f"XTerm*faceName: {colors.font_family}")
        lines.append(f"XTerm*faceSize: {colors.font_size:g}")
    return "\n".join(lines) + "\n"


def _apply_xterm(pal: MaterialPalette, settings: TerminalSettings) -> tuple[bool, str]:
    colors = resolve_terminal_colors(pal, settings)
    path = xterm_resources_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_xterm_resources(colors), encoding="utf-8")
    xrdb = shutil.which("xrdb")
    if xrdb:
        try:
            subprocess.run([xrdb, "-merge", str(path)], check=False, timeout=4)
            return True, f"wrote {path}; merged with xrdb (restart xterm to apply)"
        except (OSError, subprocess.SubprocessError):
            pass
    return True, f"wrote {path}; run 'xrdb -merge {path}' and restart xterm"


# --------------------------------------------------------------------- registry


@dataclass(frozen=True)
class TerminalBackend:
    term_id: str
    label: str
    binaries: tuple[str, ...]
    apply: Callable[[MaterialPalette, TerminalSettings], tuple[bool, str]]

    def is_installed(self) -> bool:
        return any(shutil.which(b) for b in self.binaries)


TERMINALS: dict[str, TerminalBackend] = {
    "konsole": TerminalBackend(
        "konsole", "Konsole (KDE default)", ("konsole",), _apply_konsole
    ),
    "kitty": TerminalBackend("kitty", "kitty", ("kitty",), _apply_kitty),
    "alacritty": TerminalBackend(
        "alacritty", "Alacritty", ("alacritty",), _apply_alacritty
    ),
    "xterm": TerminalBackend("xterm", "xterm", ("xterm", "uxterm"), _apply_xterm),
}


def installed_terminals() -> list[str]:
    """Backend ids whose executable is on ``PATH`` (Konsole always listed first)."""
    return [tid for tid, be in TERMINALS.items() if be.is_installed()]


def apply_terminal_theme(
    pal: MaterialPalette,
    settings: TerminalSettings | None = None,
) -> tuple[bool, str]:
    """Apply the palette to whichever terminal the user selected."""
    s = settings or load_terminal_settings()
    backend = TERMINALS.get(s.terminal_id) or TERMINALS[DEFAULT_TERMINAL_ID]
    try:
        ok, msg = backend.apply(pal, s)
    except OSError as exc:
        return False, f"{backend.term_id}: {exc}"
    return ok, f"{backend.term_id}: {msg}"
